A = list("В. М. Глушков – великий  учений України")
print(A)
print('len ->',len(A))
A.remove('.')
A.remove(' ')
print(A)
print('a ->','а' in A)
print('ю ->','ю' in A)
A += list('кібернетик')
print(A)
print('len new A ->',len(A))
